
--------------------------------------------------------
--  DDL for Table COMPANY
--------------------------------------------------------

  CREATE OR REPLACE TABLE "SYSTEM"."COMPANY" 
   (	"CNAME" VARCHAR2(255 BYTE), 
	"ZIPCODE" NUMBER, 
	"CITY" VARCHAR2(255 BYTE), 
	"NATION" VARCHAR2(255 BYTE), 
	"NUMBEROFEMPLOYEES" NUMBER, 
	"ORGANISATIONTYPE" VARCHAR2(255 BYTE), 
	"CID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE 
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table VALUATION
--------------------------------------------------------

  CREATE OR REPLACE TABLE "SYSTEM"."VALUATION" 
   (	"VALUATION_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"CID" NUMBER, 
	"CATEGORY" VARCHAR2(255 BYTE), 
	"VALUE" FLOAT(126)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table NATIONALINSURANCE
--------------------------------------------------------

  CREATE OR REPLACE TABLE "SYSTEM"."NATIONALINSURANCE" 
   (	"NIID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NINUMBER" VARCHAR2(255 BYTE), 
	"COUNTRY" VARCHAR2(255 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SHAREHOLDERS
--------------------------------------------------------

  CREATE OR REPLACE TABLE "SYSTEM"."SHAREHOLDERS" 
   (	"SID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"CID" NUMBER, 
	"SNAME" VARCHAR2(255 BYTE), 
	"BIRTHPLACE" VARCHAR2(255 BYTE), 
	"FATHERFIRSTNAME" VARCHAR2(255 BYTE), 
	"TELEPHONENUMBER" VARCHAR2(255 BYTE), 
	"PASSPORTNUMBER" NUMBER, 
	"NIID" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GRANTAPPLICATION
--------------------------------------------------------

  CREATE OR REPLACE TABLE "SYSTEM"."GRANTAPPLICATION" 
   (	"GRAID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"GRID" NUMBER, 
	"CID" NUMBER, 
	"APPLICATIONDATE" DATE, 
	"DESIREDAMOUNT" FLOAT(126), 
	"OUTCOME" VARCHAR2(255 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GRANTS
--------------------------------------------------------

  CREATE OR REPLACE TABLE "SYSTEM"."GRANTS" 
   (	"GRID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"OFFICIALTITLE" VARCHAR2(255 BYTE), 
	"FUNDINGORGANIZATION" VARCHAR2(255 BYTE), 
	"MAXIMUMMONETARYVALUE" FLOAT(126), 
	"PROPOSALDEADLINE" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table LOCALGOVT
--------------------------------------------------------

  CREATE OR REPLACE TABLE "SYSTEM"."LOCALGOVT" 
   (	"GID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"GOVTNAME" VARCHAR2(255 BYTE), 
	"REGISTRATIONFEE" VARCHAR2(255 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COMPANYREGISTRATION
--------------------------------------------------------

  CREATE OR REPLACE TABLE "SYSTEM"."COMPANYREGISTRATION" 
   (	"REGID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"GID" NUMBER, 
	"CID" NUMBER, 
	"REGISTRATIONDATE" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MOVIE
--------------------------------------------------------

  CREATE OR REPLACE TABLE "SYSTEM"."MOVIE" 
   (	"MCODE" NUMBER, 
	"CID" NUMBER, 
	"MOVIETITLE" VARCHAR2(255 BYTE), 
	"YEAR" VARCHAR2(255 BYTE), 
	"INITIALRELEASEDATE" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYEE
--------------------------------------------------------

  CREATE OR REPLACE TABLE "SYSTEM"."EMPLOYEE" 
   (	"EMPID" NUMBER, 
	"CID" NUMBER, 
	"GIVENNAME" VARCHAR2(255 BYTE), 
	"SURNAME" VARCHAR2(255 BYTE), 
	"MIDDLENAME" VARCHAR2(255 BYTE), 
	"EMAILADDRESS" VARCHAR2(255 BYTE), 
	"COMMENCEMENTDATE" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CREW
--------------------------------------------------------

  CREATE OR REPLACE TABLE "SYSTEM"."CREW" 
   (	"CREWID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"EMPID" NUMBER, 
	"FACTIONID" NUMBER, 
	"HOURLYPAY" FLOAT(126), 
	"DAILYBONUS" FLOAT(126), 
	"SCENEBONUS" FLOAT(126), 
	"SHOOTINGBONUS" FLOAT(126)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table STAFF
--------------------------------------------------------

  CREATE OR REPLACE TABLE "SYSTEM"."STAFF" 
   (	"STAFFID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"EMPID" NUMBER, 
	"FACTIONID" NUMBER, 
	"DID" NUMBER, 
	"MONTHLYWAGE" FLOAT(126), 
	"WORKINGHOURS" FLOAT(126)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CONTACTINFORMATION
--------------------------------------------------------

  CREATE OR REPLACE TABLE "SYSTEM"."CONTACTINFORMATION" 
   (	"CONTACTID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"EMPID" NUMBER, 
	"TELEPHONENUMBER" VARCHAR2(500 BYTE), 
	"DESCRIPTION" VARCHAR2(500 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DEPARTMENT
--------------------------------------------------------

  CREATE OR REPLACE TABLE "SYSTEM"."DEPARTMENT" 
   (	"DID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"DNAME" VARCHAR2(255 BYTE), 
	"DBUILDING" VARCHAR2(255 BYTE), 
	"DADDRESS" VARCHAR2(255 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FACTION
--------------------------------------------------------

  CREATE OR REPLACE TABLE "SYSTEM"."FACTION" 
   (	"FACTIONID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"FACTIONNAME" VARCHAR2(255 BYTE), 
	"CATEGORY" VARCHAR2(255 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ROLE
--------------------------------------------------------

  CREATE OR REPLACE TABLE "SYSTEM"."ROLE" 
   (	"ROLEID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"CREWID" NUMBER, 
	"MCODE" NUMBER, 
	"ROLE" VARCHAR2(255 BYTE), 
	"DESCRIPTION" VARCHAR2(255 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

--------------------------------------------------------
--  DDL for Index COMPANY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."COMPANY_PK" ON "SYSTEM"."COMPANY" ("CID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index VALUATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."VALUATION_PK" ON "SYSTEM"."VALUATION" ("VALUATION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index NATIONALINSURANCE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."NATIONALINSURANCE_PK" ON "SYSTEM"."NATIONALINSURANCE" ("NIID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SHAREHOLDERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SHAREHOLDERS_PK" ON "SYSTEM"."SHAREHOLDERS" ("SID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index GRANTAPPLICATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."GRANTAPPLICATION_PK" ON "SYSTEM"."GRANTAPPLICATION" ("GRAID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index GRANTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."GRANTS_PK" ON "SYSTEM"."GRANTS" ("GRID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index LOCALGOVT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."LOCALGOVT_PK" ON "SYSTEM"."LOCALGOVT" ("GID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index COMPANYREGISTRATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."COMPANYREGISTRATION_PK" ON "SYSTEM"."COMPANYREGISTRATION" ("REGID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MOVIE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."MOVIE_PK" ON "SYSTEM"."MOVIE" ("MCODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EMPLOYEE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."EMPLOYEE_PK" ON "SYSTEM"."EMPLOYEE" ("EMPID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CREW_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."CREW_PK" ON "SYSTEM"."CREW" ("CREWID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index STAFF_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."STAFF_PK" ON "SYSTEM"."STAFF" ("STAFFID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CONTACTINFORMATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."CONTACTINFORMATION_PK" ON "SYSTEM"."CONTACTINFORMATION" ("CONTACTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DEPARTMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."DEPARTMENT_PK" ON "SYSTEM"."DEPARTMENT" ("DID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FACTION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."FACTION_PK" ON "SYSTEM"."FACTION" ("FACTIONID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ROLE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."ROLE_PK" ON "SYSTEM"."ROLE" ("ROLEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table COMPANY
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."COMPANY" MODIFY ("CID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."COMPANY" ADD CONSTRAINT "COMPANY_PK" PRIMARY KEY ("CID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table VALUATION
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."VALUATION" MODIFY ("VALUATION_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."VALUATION" ADD CONSTRAINT "VALUATION_PK" PRIMARY KEY ("VALUATION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table NATIONALINSURANCE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."NATIONALINSURANCE" MODIFY ("NIID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."NATIONALINSURANCE" ADD CONSTRAINT "NATIONALINSURANCE_PK" PRIMARY KEY ("NIID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SHAREHOLDERS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."SHAREHOLDERS" MODIFY ("SID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."SHAREHOLDERS" ADD CONSTRAINT "SHAREHOLDERS_PK" PRIMARY KEY ("SID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."SHAREHOLDERS" MODIFY ("PASSPORTNUMBER" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GRANTAPPLICATION
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."GRANTAPPLICATION" MODIFY ("GRAID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."GRANTAPPLICATION" ADD CONSTRAINT "GRANTAPPLICATION_PK" PRIMARY KEY ("GRAID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table GRANTS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."GRANTS" MODIFY ("GRID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."GRANTS" ADD CONSTRAINT "GRANTS_PK" PRIMARY KEY ("GRID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LOCALGOVT
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."LOCALGOVT" MODIFY ("GID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."LOCALGOVT" ADD CONSTRAINT "LOCALGOVT_PK" PRIMARY KEY ("GID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table COMPANYREGISTRATION
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."COMPANYREGISTRATION" MODIFY ("REGID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."COMPANYREGISTRATION" ADD CONSTRAINT "COMPANYREGISTRATION_PK" PRIMARY KEY ("REGID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MOVIE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."MOVIE" MODIFY ("MCODE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."MOVIE" ADD CONSTRAINT "MOVIE_PK" PRIMARY KEY ("MCODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."EMPLOYEE" MODIFY ("EMPID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."EMPLOYEE" ADD CONSTRAINT "EMPLOYEE_PK" PRIMARY KEY ("EMPID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CREW
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CREW" MODIFY ("CREWID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CREW" ADD CONSTRAINT "CREW_PK" PRIMARY KEY ("CREWID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table STAFF
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."STAFF" MODIFY ("STAFFID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."STAFF" ADD CONSTRAINT "STAFF_PK" PRIMARY KEY ("STAFFID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CONTACTINFORMATION
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CONTACTINFORMATION" MODIFY ("CONTACTID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CONTACTINFORMATION" ADD CONSTRAINT "CONTACTINFORMATION_PK" PRIMARY KEY ("CONTACTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DEPARTMENT
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."DEPARTMENT" MODIFY ("DID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."DEPARTMENT" ADD CONSTRAINT "DEPARTMENT_PK" PRIMARY KEY ("DID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FACTION
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."FACTION" MODIFY ("FACTIONID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."FACTION" ADD CONSTRAINT "FACTION_PK" PRIMARY KEY ("FACTIONID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ROLE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ROLE" MODIFY ("ROLEID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ROLE" ADD CONSTRAINT "ROLE_PK" PRIMARY KEY ("ROLEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table VALUATION
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."VALUATION" ADD CONSTRAINT "VALUATION_FK1" FOREIGN KEY ("CID")
	  REFERENCES "SYSTEM"."COMPANY" ("CID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SHAREHOLDERS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."SHAREHOLDERS" ADD CONSTRAINT "SHAREHOLDERS_FK1" FOREIGN KEY ("CID")
	  REFERENCES "SYSTEM"."COMPANY" ("CID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SYSTEM"."SHAREHOLDERS" ADD CONSTRAINT "SHAREHOLDERS_FK2" FOREIGN KEY ("NIID")
	  REFERENCES "SYSTEM"."NATIONALINSURANCE" ("NIID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GRANTAPPLICATION
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."GRANTAPPLICATION" ADD CONSTRAINT "GRANTAPPLICATION_FK1" FOREIGN KEY ("GRID")
	  REFERENCES "SYSTEM"."GRANTS" ("GRID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SYSTEM"."GRANTAPPLICATION" ADD CONSTRAINT "GRANTAPPLICATION_FK2" FOREIGN KEY ("CID")
	  REFERENCES "SYSTEM"."COMPANY" ("CID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COMPANYREGISTRATION
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."COMPANYREGISTRATION" ADD CONSTRAINT "COMPANYREGISTRATION_FK1" FOREIGN KEY ("GID")
	  REFERENCES "SYSTEM"."LOCALGOVT" ("GID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SYSTEM"."COMPANYREGISTRATION" ADD CONSTRAINT "COMPANYREGISTRATION_FK2" FOREIGN KEY ("CID")
	  REFERENCES "SYSTEM"."COMPANY" ("CID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MOVIE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."MOVIE" ADD CONSTRAINT "MOVIE_FK1" FOREIGN KEY ("CID")
	  REFERENCES "SYSTEM"."COMPANY" ("CID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."EMPLOYEE" ADD CONSTRAINT "EMPLOYEE_FK1" FOREIGN KEY ("CID")
	  REFERENCES "SYSTEM"."COMPANY" ("CID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CREW
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CREW" ADD CONSTRAINT "CREW_FK1" FOREIGN KEY ("EMPID")
	  REFERENCES "SYSTEM"."EMPLOYEE" ("EMPID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SYSTEM"."CREW" ADD CONSTRAINT "CREW_FK2" FOREIGN KEY ("FACTIONID")
	  REFERENCES "SYSTEM"."FACTION" ("FACTIONID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table STAFF
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."STAFF" ADD CONSTRAINT "STAFF_FK1" FOREIGN KEY ("EMPID")
	  REFERENCES "SYSTEM"."EMPLOYEE" ("EMPID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SYSTEM"."STAFF" ADD CONSTRAINT "STAFF_FK2" FOREIGN KEY ("DID")
	  REFERENCES "SYSTEM"."DEPARTMENT" ("DID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SYSTEM"."STAFF" ADD CONSTRAINT "STAFF_FK3" FOREIGN KEY ("FACTIONID")
	  REFERENCES "SYSTEM"."FACTION" ("FACTIONID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CONTACTINFORMATION
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CONTACTINFORMATION" ADD CONSTRAINT "CONTACTINFORMATION_FK1" FOREIGN KEY ("EMPID")
	  REFERENCES "SYSTEM"."EMPLOYEE" ("EMPID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ROLE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ROLE" ADD CONSTRAINT "ROLE_FK1" FOREIGN KEY ("CREWID")
	  REFERENCES "SYSTEM"."CREW" ("CREWID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SYSTEM"."ROLE" ADD CONSTRAINT "ROLE_FK2" FOREIGN KEY ("MCODE")
	  REFERENCES "SYSTEM"."MOVIE" ("MCODE") ON DELETE CASCADE ENABLE;


REM INSERTING into SYSTEM.LOCALGOVT
SET DEFINE OFF;
Insert into SYSTEM.LOCALGOVT (GOVTNAME,REGISTRATIONFEE) values ('Sudski registar','15');
commit;


REM INSERTING into SYSTEM.COMPANY
Insert into SYSTEM.COMPANY (CNAME,ZIPCODE,CITY,NATION,NUMBEROFEMPLOYEES,ORGANISATIONTYPE) values ('CANON BALL',18980,'VENICE','GERMANY',120,'FOR PROFIT');
Insert into SYSTEM.COMPANY (CNAME,ZIPCODE,CITY,NATION,NUMBEROFEMPLOYEES,ORGANISATIONTYPE) values ('Platform Post-production',6531,'MACAU','PORTUGAL',478,'NON PROFIT');
Insert into SYSTEM.COMPANY (CNAME,ZIPCODE,CITY,NATION,NUMBEROFEMPLOYEES,ORGANISATIONTYPE) values ('LIONS GATE',10100,'MAGNOLIA','PORTUGAL',400,'NON PROFIT');
commit;


REM INSERTING into SYSTEM.COMPANYREGISTRATION
Insert into SYSTEM.COMPANYREGISTRATION (GID,CID,REGISTRATIONDATE) values (1,1,to_date('18-DEC-23','DD-MON-RR'));
commit;


REM INSERTING into SYSTEM.NATIONALINSURANCE
Insert into SYSTEM.NATIONALINSURANCE (NINUMBER,COUNTRY) values ('KX880177V','CROATIA');
Insert into SYSTEM.NATIONALINSURANCE (NINUMBER,COUNTRY) values ('DD935821X','CROATIA');
commit;

REM INSERTING into SYSTEM.SHAREHOLDERS
Insert into SYSTEM.SHAREHOLDERS (CID,SNAME,BIRTHPLACE,FATHERFIRSTNAME,TELEPHONENUMBER,PASSPORTNUMBER,NIID) values (1,'Charles Murphy','Sadsburyville','Campbell','+3515627055873',39058,1);
Insert into SYSTEM.SHAREHOLDERS (CID,SNAME,BIRTHPLACE,FATHERFIRSTNAME,TELEPHONENUMBER,PASSPORTNUMBER,NIID) values (1,'Collin Tiley','Canterburly','Campbell','+3510327055873',250390,2);
commit;


REM INSERTING into SYSTEM.EMPLOYEE
Insert into SYSTEM.EMPLOYEE (EMPID,CID,GIVENNAME,SURNAME,MIDDLENAME,EMAILADDRESS,COMMENCEMENTDATE) values (9904,2,'CAMRON','DENNIS','Huang','c.dl@gmail.com',to_date('19-DEC-23','DD-MON-RR'));
Insert into SYSTEM.EMPLOYEE (EMPID,CID,GIVENNAME,SURNAME,MIDDLENAME,EMAILADDRESS,COMMENCEMENTDATE) values (9905,2,'BLAKEY','Allen','Long','b.allen@rocketmail.com',to_date('19-DEC-23','DD-MON-RR'));
Insert into SYSTEM.EMPLOYEE (EMPID,CID,GIVENNAME,SURNAME,MIDDLENAME,EMAILADDRESS,COMMENCEMENTDATE) values (9906,2,'BOSNIAN','Hague','Kong','kongking@hotmail.com',to_date('19-DEC-23','DD-MON-RR'));
commit;


REM INSERTING into SYSTEM.CONTACTINFORMATION
Insert into SYSTEM.CONTACTINFORMATION (EMPID,TELEPHONENUMBER,DESCRIPTION) values (9904,'+35190009283','Main Number');
Insert into SYSTEM.CONTACTINFORMATION (EMPID,TELEPHONENUMBER,DESCRIPTION) values (9905,'+35198877200','Secondary Number');
commit;


REM INSERTING into SYSTEM.DEPARTMENT
Insert into SYSTEM.DEPARTMENT (DNAME,DBUILDING,DADDRESS) values ('Accounting','AC h02','6664 Washington Street');
Insert into SYSTEM.DEPARTMENT (DNAME,DBUILDING,DADDRESS) values ('Marketing','Mk HQ','523 New Street');
commit;


REM INSERTING into SYSTEM.FACTION
Insert into SYSTEM.FACTION (FACTIONNAME,CATEGORY) values ('Accounting','Staff');
Insert into SYSTEM.FACTION (FACTIONNAME,CATEGORY) values ('Marketing','Staff');
Insert into SYSTEM.FACTION (FACTIONNAME,CATEGORY) values ('Actor','Crew');
Insert into SYSTEM.FACTION (FACTIONNAME,CATEGORY) values ('Director','Crew');
Insert into SYSTEM.FACTION (FACTIONNAME,CATEGORY) values ('Production Team','Crew');
commit;


REM INSERTING into SYSTEM.CREW
Insert into SYSTEM.CREW (EMPID,FACTIONID,HOURLYPAY,DAILYBONUS,SCENEBONUS,SHOOTINGBONUS) values (9904,4,35,0,0,1500);
commit;


REM INSERTING into SYSTEM.STAFF
Insert into SYSTEM.STAFF (EMPID,FACTIONID,DID,MONTHLYWAGE,WORKINGHOURS) values (9905,1,1,3409900,4.6);
commit;



REM INSERTING into SYSTEM.MOVIE
Insert into SYSTEM.MOVIE (MCODE,CID,MOVIETITLE,YEAR,INITIALRELEASEDATE) values (202,2,'Chan Is Missing ','2023',to_date('18-DEC-23','DD-MON-RR'));
Insert into SYSTEM.MOVIE (MCODE,CID,MOVIETITLE,YEAR,INITIALRELEASEDATE) values (205,2,'The Bargain ','2022',to_date('05-NOV-22','DD-MON-RR'));
commit;


REM INSERTING into SYSTEM.ROLE
Insert into SYSTEM.ROLE (CREWID,MCODE,ROLE,DESCRIPTION) values (1,202,'Protagonis','Acted as the main bad guy');
commit;


REM INSERTING into SYSTEM.GRANTAPPLICATION
Insert into SYSTEM.GRANTAPPLICATION (CID,APPLICATIONDATE,DESIREDAMOUNT,OUTCOME) values (2,to_date('19-DEC-23','DD-MON-RR'),37889,null);
Insert into SYSTEM.GRANTAPPLICATION (CID,APPLICATIONDATE,DESIREDAMOUNT,OUTCOME) values (2,to_date('20-DEC-23','DD-MON-RR'),48985,null);
commit;


































