
CREATE TABLE CAR (
CAR_NR NUMBER NOT NULL ENABLE, 
CAR_TYPE VARCHAR2(1000 CHAR) NOT NULL ENABLE, 
constraint car_pk PRIMARY KEY(CAR_NR)
);

CREATE TABLE CUSTOMER (
CUST_NR NUMBER NOT NULL ENABLE, 
CUST_NAME VARCHAR2(1000 CHAR) NOT NULL ENABLE, 
constraint customer_pk PRIMARY KEY(CUST_NR)
);

CREATE TABLE SOBER_CAR (
CAR_NR NUMBER NOT NULL ENABLE, 
constraint sober_car_pk PRIMARY KEY(CAR_NR)
);

CREATE TABLE OTHER_CAR (
CAR_NR NUMBER NOT NULL ENABLE, 
CUST_NR NUMBER NOT NULL ENABLE, 
constraint other_car_pk PRIMARY KEY(CAR_NR),
constraint fk_customer FOREIGN KEY (CUST_NR) REFERENCES CUSTOMER(CUST_NR)
);

CREATE TABLE ACCIDENT (
ACC_NR NUMBER NOT NULL ENABLE, 
CAR_NR NUMBER NOT NULL ENABLE, 
DAMAGE_AMOUNT BINARY_DOUBLE NOT NULL ENABLE,
ACC_LOCATION VARCHAR2(1000 CHAR) NOT NULL ENABLE, 
ACC_DATE_TIME TIMESTAMP NOT NULL ENABLE,

constraint accident_pk PRIMARY KEY(ACC_NR),
constraint fk_car FOREIGN KEY (CAR_NR) REFERENCES CAR(CAR_NR)
);


CREATE TABLE RIDE (
RIDE_NR NUMBER NOT NULL ENABLE,
CAR_NR NUMBER NOT NULL ENABLE,
PICKUP_LOC VARCHAR2(1000 CHAR) NOT NULL ENABLE, 
PICKUP_DATE_TIME TIMESTAMP NOT NULL ENABLE, 
DROPOFF_DATE_TIME TIMESTAMP NOT NULL ENABLE,
DURATION BINARY_DOUBLE NOT NULL ENABLE, 
FEE BINARY_DOUBLE NOT NULL ENABLE,

constraint ride_pk PRIMARY KEY(RIDE_NR,DURATION),
constraint fk_car FOREIGN KEY (CAR_NR) REFERENCES CAR(CAR_NR)
);


CREATE TABLE RIDE_HAILING (
RIDE_NR NUMBER NOT NULL ENABLE,
CUST_NR NUMBER NOT NULL ENABLE,
DURATION BINARY_DOUBLE NOT NULL ENABLE, 
PASSENGERS NUMBER NOT NULL ENABLE,
WAIT_TIME TIMESTAMP NOT NULL ENABLE,
REQUEST_TYPE VARCHAR2(1000 CHAR) NOT NULL ENABLE, 

constraint ride_hailing_pk PRIMARY KEY(RIDE_NR,DURATION),
constraint fk_customer FOREIGN KEY (CUST_NR) REFERENCES CUSTOMER(CUST_NR)
);


CREATE TABLE RIDE_SHARING (
RIDE_NR NUMBER NOT NULL ENABLE,
CUST_NR NUMBER NOT NULL ENABLE,
DURATION BINARY_DOUBLE NOT NULL ENABLE, 

constraint ride_hailing_pk PRIMARY KEY(RIDE_NR,DURATION),
constraint fk_customer FOREIGN KEY (CUST_NR) REFERENCES CUSTOMER(CUST_NR)
);